import Head from 'next/head';
import Link from 'next/link';
import Header from '@/components/Header';
import styles from '@/styles/Legal.module.css';

export default function TermsOfService() {
  const lastUpdated = 'December 10, 2025';

  return (
    <>
      <Head>
        <title>Terms of Service | HALCYON-Cinema</title>
        <meta name="description" content="Terms of Service for HALCYON-Cinema AI-powered cinematic content studio" />
      </Head>

      <Header />

      <main className="page">
        <div className="container">
          <article className={styles.legal}>
            <header className={styles.header}>
              <h1 className={styles.title}>Terms of Service</h1>
              <p className={styles.updated}>Last updated: {lastUpdated}</p>
            </header>

            <section className={styles.section}>
              <h2>1. Acceptance of Terms</h2>
              <p>
                By accessing or using HALCYON-Cinema (&ldquo;Service&rdquo;), you agree to be bound by these
                Terms of Service. If you do not agree to these terms, please do not use our Service.
              </p>
            </section>

            <section className={styles.section}>
              <h2>2. Description of Service</h2>
              <p>
                HALCYON-Cinema is an AI-powered cinematic content studio that enables users to create
                scenes, storyboards, and visual content using artificial intelligence technology,
                specifically OpenAI&apos;s DALL-E 3 image generation model.
              </p>
            </section>

            <section className={styles.section}>
              <h2>3. AI-Generated Content Disclosure</h2>
              <div className={styles.highlight}>
                <p>
                  <strong>Important:</strong> All images and visual content created through HALCYON-Cinema
                  are generated by artificial intelligence (AI). This content:
                </p>
                <ul>
                  <li>Is created using OpenAI&apos;s DALL-E 3 image generation technology</li>
                  <li>May not accurately represent real people, places, or events</li>
                  <li>Should be clearly labeled as AI-generated when shared publicly</li>
                  <li>Must not be used to create deceptive or misleading content</li>
                </ul>
              </div>
            </section>

            <section className={styles.section}>
              <h2>4. User Accounts</h2>
              <p>
                To use certain features of the Service, you must create an account. You are responsible for:
              </p>
              <ul>
                <li>Maintaining the confidentiality of your account credentials</li>
                <li>All activities that occur under your account</li>
                <li>Notifying us immediately of any unauthorized use</li>
              </ul>
            </section>

            <section className={styles.section}>
              <h2>5. Acceptable Use</h2>
              <p>You agree NOT to use the Service to:</p>
              <ul>
                <li>Generate content depicting real individuals without their consent</li>
                <li>Create harmful, abusive, or illegal content</li>
                <li>Generate content that infringes on intellectual property rights</li>
                <li>Create deepfakes or deceptive media intended to mislead</li>
                <li>Produce content depicting minors in any inappropriate context</li>
                <li>Generate violent, hateful, or discriminatory content</li>
                <li>Violate any applicable laws or regulations</li>
              </ul>
            </section>

            <section className={styles.section}>
              <h2>6. Content Ownership and Rights</h2>
              <p>
                Subject to compliance with these Terms:
              </p>
              <ul>
                <li>
                  You retain ownership of the text prompts you submit to the Service
                </li>
                <li>
                  AI-generated images are provided for your use in accordance with OpenAI&apos;s usage policies
                </li>
                <li>
                  You may use generated content for personal and commercial purposes, subject to applicable
                  laws and these Terms
                </li>
                <li>
                  We do not claim ownership of content you create using the Service
                </li>
              </ul>
            </section>

            <section className={styles.section}>
              <h2>7. Usage Limits and Credits</h2>
              <p>
                The Service operates on a credit-based system. Free accounts receive a limited number
                of credits. Usage limits may apply, and we reserve the right to modify these limits
                at any time.
              </p>
            </section>

            <section className={styles.section}>
              <h2>8. Intellectual Property</h2>
              <p>
                The HALCYON-Cinema brand, logo, software, and associated materials are protected by
                intellectual property laws. You may not copy, modify, or distribute our proprietary
                materials without express permission.
              </p>
            </section>

            <section className={styles.section}>
              <h2>9. Disclaimer of Warranties</h2>
              <p>
                THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; WITHOUT WARRANTIES OF ANY KIND. WE DO NOT GUARANTEE
                THAT AI-GENERATED CONTENT WILL MEET YOUR SPECIFIC REQUIREMENTS OR EXPECTATIONS.
                RESULTS MAY VARY.
              </p>
            </section>

            <section className={styles.section}>
              <h2>10. Limitation of Liability</h2>
              <p>
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, HALCYON-CINEMA SHALL NOT BE LIABLE FOR ANY
                INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR
                USE OF THE SERVICE.
              </p>
            </section>

            <section className={styles.section}>
              <h2>11. Termination</h2>
              <p>
                We reserve the right to suspend or terminate your account at any time for violations
                of these Terms or for any other reason at our sole discretion.
              </p>
            </section>

            <section className={styles.section}>
              <h2>12. Changes to Terms</h2>
              <p>
                We may update these Terms from time to time. We will notify users of significant
                changes. Continued use of the Service after changes constitutes acceptance of the
                new Terms.
              </p>
            </section>

            <section className={styles.section}>
              <h2>13. Contact</h2>
              <p>
                For questions about these Terms, please contact us at legal@halcyon-cinema.com
              </p>
            </section>

            <div className={styles.footer}>
              <Link href="/privacy" className={styles.link}>
                Privacy Policy
              </Link>
              <span className={styles.separator}>|</span>
              <Link href="/" className={styles.link}>
                Return to Home
              </Link>
            </div>
          </article>
        </div>
      </main>
    </>
  );
}
